version: "3.7"

services:
  nodejs-api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    container_name: nodejs-api
    links:
      - mongodb
    volumes: [
      ./:/app
      /app/node_modules
    ]
    depends_on:
      - mongodb
    networks:
      - backend
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - ./db/:/data/db
    networks:
      - backend
networks: 
  backend: